#!/usr/bin/env bash
# herdr module: herdr binary, lazygit, config.toml and pinned plugins.
#
#   herdr/install.sh [--profile mac|ubuntu|vps] [--dry-run]
#
# config.toml = config.base.toml + profiles/<profile>.toml (TOML concatenation:
# a profile may only add tables the base does not define). Line 1 of the
# profile must be "# keymap-modifier: cmd|alt"; that value replaces every
# {{mod}} and the directive line itself is not copied. Base lines starting with
# "#%" document the template and are dropped. The result is validated with
# `herdr config check` before it replaces the live file. --dry-run still
# renders, validates and diffs, but changes nothing on disk.
set -euo pipefail

# shellcheck source=../lib/common.sh
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common.sh"
parse_args "$@"

here="$DOTFILES_ROOT/herdr"
config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/herdr"
target="$config_dir/config.toml"
scratch="$(mktemp -d)"
trap 'rm -rf "$scratch"' EXIT

# --- herdr -------------------------------------------------------------------
step "herdr"
if have herdr; then
  log "$(herdr --version): ok"
else
  have curl || die "herdr is missing and curl is not installed; install curl and re-run"
  log "herdr: install via https://herdr.dev/install.sh (into ~/.local/bin)"
  run bash -o pipefail -c 'curl -fsSL https://herdr.dev/install.sh | sh'
  $DRY_RUN || have herdr || die "herdr install failed: ~/.local/bin/herdr not found (manual install: https://herdr.dev/docs/install/)"
fi

# --- lazygit (runtime dependency of the git-status popup) --------------------
install_lazygit_linux() {
  local arch tag url
  case "$(uname -m)" in
    x86_64 | amd64) arch=x86_64 ;;
    aarch64 | arm64) arch=arm64 ;;
    *) die "lazygit: no Linux release tarball for $(uname -m); install lazygit manually" ;;
  esac
  have curl || die "lazygit is missing and curl is not installed; install curl and re-run"
  # /releases/latest redirects to /releases/tag/vX.Y.Z; no API token or rate limit.
  tag="$(curl -fsSLI -o /dev/null -w '%{url_effective}' https://github.com/jesseduffield/lazygit/releases/latest)"
  tag="${tag##*/}"
  [[ "$tag" == v[0-9]* ]] || die "lazygit: could not resolve the latest release tag (got '$tag')"
  url="https://github.com/jesseduffield/lazygit/releases/download/$tag/lazygit_${tag#v}_linux_$arch.tar.gz"
  log "lazygit: install $tag ($arch) into ~/.local/bin"
  run curl -fsSL --retry 3 -o "$scratch/lazygit.tar.gz" "$url"
  run tar -xzf "$scratch/lazygit.tar.gz" -C "$scratch" lazygit
  run mkdir -p "$HOME/.local/bin"
  run install -m 0755 "$scratch/lazygit" "$HOME/.local/bin/lazygit"
}

step "lazygit"
if have lazygit; then
  log "lazygit: ok"
elif [[ "$(detect_os)" == macos ]]; then
  have brew || die "lazygit is missing and Homebrew is not installed; install Homebrew (https://brew.sh) and re-run"
  run brew install lazygit
else
  install_lazygit_linux
fi

# The mac profile pins fish rather than inheriting an obsolete $SHELL. Homebrew's
# prefix differs between Apple Silicon and Intel, so render its actual path.
fish_shell=""
if [[ "$PROFILE" == mac ]]; then
  step "fish (herdr default shell)"
  have brew || die "mac profile requires Homebrew fish; install Homebrew (https://brew.sh) and retry"
  fish_shell="$(brew --prefix)/bin/fish"
  if [[ ! -x "$fish_shell" ]]; then
    run brew install fish
    $DRY_RUN || [[ -x "$fish_shell" ]] || die "fish not found at $fish_shell after brew install"
  else
    log "$fish_shell: ok"
  fi
fi

# --- config.toml -------------------------------------------------------------
step "config.toml (profile: $PROFILE)"
profile_file="$here/profiles/$PROFILE.toml"
[[ -f "$profile_file" ]] || die "profile file not found: $profile_file"
directive=""
IFS= read -r directive <"$profile_file" || true
case "$directive" in
  "# keymap-modifier: cmd") mod=cmd ;;
  "# keymap-modifier: alt") mod=alt ;;
  *) die "$profile_file: line 1 must be '# keymap-modifier: cmd' or '# keymap-modifier: alt' (got: '$directive')" ;;
esac

mkdir -p "$scratch/herdr"
rendered="$scratch/herdr/config.toml"
{
  echo "# Generated by dotfiles/herdr/install.sh (profile: $PROFILE, keymap-modifier: $mod). Edit the sources, not this file."
  sed '/^#%/d' "$here/config.base.toml"
  echo
  echo "# --- profile: $PROFILE ---"
  sed '1d' "$profile_file"
} | sed -e "s/{{mod}}/$mod/g" -e "s#{{fish_shell}}#$fish_shell#g" >"$rendered"

if grep -q '{{' "$rendered"; then
  die "unresolved placeholder in rendered config: $(grep -n '{{' "$rendered" | sed -n '1p')"
fi
log "keymap modifier: $mod"

if have herdr; then
  if check_out="$(XDG_CONFIG_HOME="$scratch" herdr config check 2>&1)"; then
    log "herdr config check: $check_out"
  else
    printf '%s\n' "$check_out" >&2
    die "rendered config is invalid; nothing installed"
  fi
else
  warn "herdr is not installed yet: rendered config not validated (dry-run)"
fi

if [[ -f "$target" ]] && cmp -s "$target" "$rendered"; then
  log "config.toml: up to date"
else
  if [[ -f "$target" ]]; then
    diff -u "$target" "$rendered" || true
  else
    log "config.toml: new file $target"
  fi
  run mkdir -p "$config_dir"
  backup "$target"
  run cp "$rendered" "$target"
  $DRY_RUN || log "config.toml: installed"
fi

# --- plugins -----------------------------------------------------------------
# Build steps of the pins in plugins.txt (their herdr-plugin.toml [[build]]):
# annotate, persiyanov.reviewr and herdr-file-viewer download prebuilt,
# checksum-verified binaries (curl + sha256sum/shasum); herdr-automatic-rename
# has no build. herdr-file-viewer only ships prebuilt binaries for macOS and
# Linux x86_64; anywhere else it builds from source with cargo (Rust 1.96+).
# Prints a reason and returns 1 when the plugin cannot be built here.
plugin_build_ready() {
  case "$1" in
    herdr-file-viewer)
      [[ "$(detect_os)" == macos || "$(uname -m)" == x86_64 ]] && return 0
      { have cargo || [[ -x "$HOME/.cargo/bin/cargo" ]]; } && return 0
      echo "$1 has no prebuilt binary for linux/$(uname -m) and builds with cargo, which is missing; install Rust 1.96+ (https://rustup.rs) and re-run"
      return 1
      ;;
  esac
}

step "plugins"
plugin_line() { herdr plugin list 2>/dev/null | grep -E "^- ${1//./\\.} " || true; }
while read -r -u 3 id source ref state; do
  [[ -z "$id" || "$id" == \#* ]] && continue
  line="$(plugin_line "$id")"
  if [[ "$line" == *"@$ref]"* ]]; then
    log "plugin $id: at $ref"
  else
    log "plugin $id: install $source@$ref"
    if ! reason="$(plugin_build_ready "$id")"; then
      $DRY_RUN || die "$reason"
      warn "$reason"
    fi
    if [[ -n "$line" ]]; then
      run herdr plugin uninstall "$id"
    fi
    # Positional first: herdr 0.9.1's parser rejects options before it.
    run herdr plugin install "$source" --ref "$ref" --yes
    $DRY_RUN || line="$(plugin_line "$id")"
  fi
  if [[ -n "$line" && "$line" != *") $state ["* ]]; then
    log "plugin $id: set $state"
    run herdr plugin "${state%d}" "$id"
  fi
done 3<"$here/plugins.txt"

# --- plugin config -----------------------------------------------------------
step "plugin config"
for dir in "$here"/plugin-config/*/; do
  id="$(basename "$dir")"
  dest="$config_dir/plugins/config/$id"
  for file in "$dir"*; do
    name="$(basename "$file")"
    if cmp -s "$file" "$dest/$name"; then
      log "plugin-config $id/$name: up to date"
    else
      log "plugin-config $id/$name: install"
      run mkdir -p "$dest"
      run cp "$file" "$dest/$name"
    fi
  done
done

# --- running server ----------------------------------------------------------
step "herdr server"
# `herdr status server` exits 0 even when stopped; the status line is the signal.
if have herdr && [[ "$(herdr status server 2>/dev/null)" == "status: running"* ]]; then
  if run herdr server reload-config; then
    $DRY_RUN || log "server: config reloaded"
  else
    warn "herdr server reload-config failed; restart herdr to apply the new config"
  fi
else
  log "server: not running"
fi

# reviewr's editor (plugin-config/persiyanov.reviewr) is Neovim; not managed here.
have nvim || warn "nvim not found: reviewr opens files with 'nvim +{line} {file}'; install Neovim"
