#!/usr/bin/env bash
# Install herdr config + plugins for one machine profile.
#
#   herdr/install.sh <profile> [--dry-run]
#
# config.toml = config.base.toml + profiles/<profile>.toml (TOML concatenation:
# a profile may only add tables the base does not define). The result is
# validated with `herdr config check` before it replaces the live file.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
profile="${1:-}"
dry_run=false
[[ "${2:-}" == "--dry-run" ]] && dry_run=true

profiles=$(cd "$here/profiles" && ls ./*.toml | sed 's|^\./||; s|\.toml$||' | tr '\n' ' ')
if [[ -z "$profile" || ! -f "$here/profiles/$profile.toml" ]]; then
  echo "usage: $0 <profile> [--dry-run]   profiles: $profiles" >&2
  exit 2
fi

herdr_bin="$(command -v herdr || true)"
[[ -z "$herdr_bin" && -x "$HOME/.local/bin/herdr" ]] && herdr_bin="$HOME/.local/bin/herdr"
if [[ -z "$herdr_bin" ]]; then
  echo "herdr not found (install: https://herdr.dev)" >&2
  exit 1
fi

config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/herdr"
target="$config_dir/config.toml"

# --- config.toml ---------------------------------------------------------
stage="$(mktemp -d)"
trap 'rm -rf "$stage"' EXIT
mkdir -p "$stage/herdr"
{
  echo "# Generated by dotfiles/herdr/install.sh (profile: $profile). Edit the sources, not this file."
  cat "$here/config.base.toml"
  echo
  echo "# --- profile: $profile ---"
  cat "$here/profiles/$profile.toml"
} >"$stage/herdr/config.toml"

if ! XDG_CONFIG_HOME="$stage" "$herdr_bin" config check; then
  echo "rendered config is invalid; nothing installed" >&2
  exit 1
fi

if [[ -f "$target" ]] && cmp -s "$target" "$stage/herdr/config.toml"; then
  echo "config.toml: up to date"
else
  diff -u "$target" "$stage/herdr/config.toml" 2>/dev/null || true
  if ! $dry_run; then
    mkdir -p "$config_dir"
    [[ -f "$target" ]] && cp "$target" "$target.bak-$(date +%Y%m%d%H%M%S)"
    cp "$stage/herdr/config.toml" "$target"
    echo "config.toml: installed (previous file backed up)"
  fi
fi

# --- plugins -------------------------------------------------------------
plugin_line() { "$herdr_bin" plugin list 2>/dev/null | grep -E "^- ${1//./\\.} " || true; }
while read -r -u 3 id source ref state; do
  [[ -z "$id" || "$id" == \#* ]] && continue
  line="$(plugin_line "$id")"
  if [[ "$line" == *"@$ref]"* ]]; then
    echo "plugin $id: at $ref"
  else
    echo "plugin $id: install $source@$ref"
    if ! $dry_run; then
      [[ -n "$line" ]] && "$herdr_bin" plugin uninstall "$id"
      "$herdr_bin" plugin install --yes --ref "$ref" "$source"
      line="$(plugin_line "$id")"
    fi
  fi
  if [[ -n "$line" && "$line" != *") $state ["* ]]; then
    echo "plugin $id: set $state"
    $dry_run || "$herdr_bin" plugin "${state%d}" "$id"
  fi
done 3<"$here/plugins.txt"

# --- plugin config ----------------------------------------------------------
for dir in "$here"/plugin-config/*/; do
  id="$(basename "$dir")"
  dest="$config_dir/plugins/config/$id"
  for file in "$dir"*; do
    name="$(basename "$file")"
    if cmp -s "$file" "$dest/$name"; then
      echo "plugin-config $id/$name: up to date"
    else
      echo "plugin-config $id/$name: install"
      $dry_run || { mkdir -p "$dest"; cp "$file" "$dest/$name"; }
    fi
  done
done

if ! $dry_run && "$herdr_bin" status server >/dev/null 2>&1; then
  "$herdr_bin" server reload-config && echo "server: config reloaded"
fi
